use std::path::{Path, PathBuf};

const HAML_BOILERPLATE: &str = r#"%DocumentLayout(size="a4")
  %Header(title="{{ title }}" subtitle="{{ subtitle }}")
  %Card(title="Summary")
    %p Hello, {{ name }}!
  - for item in items
    %p {{ item }}
"#;

const DATA_MOCK: &str = r#"{
  "title": "Sample Document",
  "subtitle": "Generated by pdfcn",
  "name": "World",
  "items": ["First item", "Second item"]
}
"#;

pub fn run(template: &str, dir: Option<&Path>) -> anyhow::Result<()> {
    let target: PathBuf = dir
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from(template));
    std::fs::create_dir_all(&target)?;

    let haml_path = target.join(format!("{template}.haml"));
    if haml_path.exists() {
        anyhow::bail!("{haml_path:?} already exists, refusing to overwrite");
    }
    std::fs::write(&haml_path, HAML_BOILERPLATE)?;

    let data_path = target.join("data.json");
    if !data_path.exists() {
        std::fs::write(&data_path, DATA_MOCK)?;
    }

    println!("Created {haml_path:?} and {data_path:?}");
    println!(
        "Try: pdfcn build {} -d {} -o out.pdf",
        haml_path.display(),
        data_path.display()
    );
    Ok(())
}
